apiVersion: v1
kind: Service
metadata:
  name: todo-api
spec:
  type: NodePort
  selector:
    app: todo-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30100
      name: http
